      data  alfa1/4.2e-7/,r1,r3/0.8,0.5/
      data alyam1,   alyam3,  alyam4 ,  alyam6,   alyam7
     *    /4.4e-10,  5.e-16,  1.4e-10,     0.0,   5.e-12/
     *    ,alyam8,   alyam9,  alyam10, alyam11,  alyam12
     *    /4.4e-12, 4.5e-13,  3.4e-11, 3.6e-10,  7.0e-11/
     *    ,alyam13, alyam14,  alyam15, alyam16
     *    /1.06e-5,  4.5e-6,  4.2e-33,  2.3e-14/
     *    ,alyam2 /1.2e-10/,alyam17/5.0e-11/
